### ISSUE TITLE
Uncaught SyntaxError

### ISSUE THREAD

**Issue by lowkey-chris** [jpoep/garmin-connect-export#1]
Hey, everytime I try to run the code, I get following error:

"Uncaught SyntaxError: Identifier 'downloadUrl' has already been declared"

<img width="555" alt="Bildschirmfoto 2023-04-25 um 14 54 56" src="https://user-images.githubusercontent.com/131777834/234282808-e21f6c65-444a-4359-8404-0b0c5cd52139.png">

**Comment by jpoep** [comment]
Yeah it's currently a little clunky to re-run the script because everything is defined as a const. It should work if you completely refresh the site using F5 and then paste the code again. 

After you've pasted the code once, it's enough to type `downloadActivities()` in the console to rerun the download. I'll try to release a version later this evening that still works if you paste the entire code multiple times :)

Let me know if that helped!

**Comment by lowkey-chris** [comment]
It was working now, but stopped after downloading 10 files. When I try to rerun the code, it just downloads the 10 files again.

**Comment by jpoep** [comment]
Is it possible that you only have 10 activities logged within your defined time period? Note that the script defaults to 2022-2020, so you'd have to change it to 2023 to include the current year. Near the top of the script, you can change `yearsTo` to 2023 as described in the README :)

**Comment by jpoep** [comment]
I actually just retested it in Chrome and it behaves similarly to what you described - it shows the names of all activities it found but stops downloading after 20 or so. Is it possible for you to retry it in Firefox? Firefox works perfectly for me.

**Comment by lowkey-chris** [comment]
It works perfectly in Firefox. Thanks :)
